import "./globals.css";
import { HeaderMenu } from "@/components/HeaderMenu";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Toaster } from "@/components/Sonner";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gamers Pub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className="overflow-hidden">
      <body className={cn(inter.className, 'overflow-hidden')}>
        <main className="w-screen h-screen overflow-y-auto">
          <HeaderMenu />
          {children}
        </main>
        <Toaster />
      </body>
    </html>
  );
}
